export const calendarEvents = {
  spring: [
    {
      day: 4,
      name: "Kent",
      type: "birthday",
      loves: ["Fiddlehead Risotto", "Roasted Hazelnuts"],
      likes: ["Daffodil", "Eggs", "Fruit"]
    },
    {
      day: 7,
      name: "Lewis",
      type: "birthday",
      loves: [
        "Autumn's Bounty",
        "Glazed Yams",
        "Hot Pepper",
        "Vegetable Medley"
      ],
      likes: ["Blueberry", "Cactus Fruit", "Coconut"]
    },
    {
      day: 10,
      name: "Vincent",
      type: "birthday",
      loves: ["Cranberry Candy", "Grape", "Pink Cake"],
      likes: ["Coconut", "Daffodil"]
    },
    { day: 13, name: "Egg Festival", type: "event" },
    {
      day: 14,
      name: "Haley",
      type: "birthday",
      loves: ["Coconut", "Fruit Salad", "Pink Cake", "Sunflower"],
      likes: ["Daffodil"]
    },
    {
      day: 18,
      name: "Pam",
      type: "birthday",
      loves: [
        "Beer",
        "Cactus Fruit",
        "Glazed Yams",
        "Mead",
        "Pale Ale",
        "Parsnip",
        "Parsnip Soup"
      ],
      likes: ["Daffodil", "Fruit", "Milk"]
    },
    {
      day: 20,
      name: "Shane",
      type: "birthday",
      loves: ["Beer", "Hot Pepper", "Pepper Poppers", "Pizza"],
      likes: ["Eggs", "Fruit"]
    },
    { day: 24, name: "Flower Dance", type: "event" },
    {
      day: 26,
      name: "Pierre",
      type: "birthday",
      loves: ["Fried Calamari"],
      likes: ["Eggs", "Milk", "Daffodil", "Dandelion"]
    },
    {
      day: 27,
      name: "Emily",
      type: "birthday",
      loves: [
        "Amethyst",
        "Aquamarine",
        "Cloth",
        "Emerald",
        "Jade",
        "Ruby",
        "Survival Burger",
        "Topaz",
        "Wool"
      ],
      likes: ["Daffodil", "Quartz"]
    }
  ],
  summer: [
    {
      day: 4,
      name: "Jas",
      type: "birthday",
      loves: ["Fairy Rose", "Pink Cake", "Plum Pudding"],
      likes: ["Coconut", "Daffodil"]
    },
    {
      day: 8,
      name: "Gus",
      type: "birthday",
      loves: ["Diamond", "Escargot", "Fish Taco", "Orange"],
      likes: ["Daffodil"]
    },
    {
      day: 10,
      name: "Maru",
      type: "birthday",
      loves: [
        "Battery Pack",
        "Cauliflower",
        "Cheese Cauliflower",
        "Diamond",
        "Gold Bar",
        "Iridium Bar",
        "Miner's Treat",
        "Pepper Poppers",
        "Rhubarb Pie",
        "Strawberry"
      ],
      likes: ["Copper Bar", "Iron Bar", "Oak Resin", "Pine Tar", "Quartz"]
    },
    {
      day: 11,
      name: "Luau",
      type: "event",
      options: {
        best: {
          Silver: [
            "Ancient Fruit Wine",
            "Apple Wine",
            "Blobfish",
            "Coconut Wine",
            "Crimsonfish",
            "Crystal Fruit Wine",
            "Goat Cheese",
            "Ice Pip",
            "Large Goat Milk",
            "Lava Eel",
            "Legend",
            "Melon Wine",
            "Orange Wine",
            "Pale Ale",
            "Peach Wine",
            "Pomegranate Wine",
            "Rhubarb Wine",
            "Starfruit",
            "Starfruit Wine",
            "Strawberry Wine",
            "Wine (from Traveling Cart)"
          ],
          "Gold/Iridium": [
            "Ancient Fruit Wine",
            "Angler",
            "Apple Wine",
            "Artichoke",
            "Beer",
            "Cactus Fruit Wine",
            "Catfish",
            "Cauliflower",
            "Chanterelle",
            "Cheese",
            "Cherry Wine",
            "Coconut Wine",
            "Cranberries Wine",
            "Crimsonfish",
            "Crystal Fruit Wine",
            "Fairy Rose",
            "Glacierfish",
            "Goat Cheese",
            "Goat Milk",
            "Grape Wine",
            "Ice Pip",
            "Large Goat Milk",
            "Large Milk",
            "Lava Eel",
            "Legend",
            "Mead",
            "Melon",
            "Melon Wine",
            "Mutant Carp",
            "Orange Wine",
            "Pale Ale",
            "Peach Wine",
            "Pomegranate Wine",
            "Purple Mushroom",
            "Red Cabbage",
            "Rhubarb Wine",
            "Spice Berry Wine",
            "Starfruit",
            "Starfruit Wine",
            "Strawberry Wine",
            "Sturgeon",
            "Super Cucumber",
            "Truffle",
            "Wild Plum Wine",
            "Wine (from Traveling Cart)",
            "Yam"
          ]
        },
        good: {
          normal: [
            "Amaranth",
            "Ancient Fruit Wine",
            "Angler",
            "Apple",
            "Apple Wine",
            "Apricot Wine",
            "Artichoke",
            "Beer",
            "Beet",
            "Blackberry Wine",
            "Blobfish",
            "Blueberry Wine",
            "Cactus Fruit",
            "Cactus Fruit Wine",
            "Catfish",
            "Cauliflower",
            "Chanterelle",
            "Cheese",
            "Cherry Wine",
            "Coconut Wine",
            "Coffee",
            "Cranberries Wine",
            "Crimsonfish",
            "Crystal Fruit",
            "Crystal Fruit Wine",
            "Dorado",
            "Energy Tonic",
            "Fairy Rose",
            "Glacierfish",
            "Goat Cheese",
            "Goat Milk",
            "Grape Wine",
            "Hot Pepper Wine",
            "Ice Pip",
            "Juice (any, including from the Traveling Cart)",
            "Kale",
            "Large Goat Milk",
            "Large Milk",
            "Largemouth Bass",
            "Lava Eel",
            "Legend",
            "Lingcod",
            "Maple Syrup",
            "Mead",
            "Melon",
            "Melon Wine",
            "Midnight Squid",
            "Milk",
            "Morel",
            "Muscle Remedy",
            "Mutant Carp",
            "Oil",
            "Orange",
            "Orange Wine",
            "Pale Ale",
            "Peach",
            "Peach Wine",
            "Pike",
            "Pomegranate",
            "Pomegranate Wine",
            "Poppy",
            "Purple Mushroom",
            "Red Cabbage",
            "Rhubarb Wine",
            "Rice",
            "Salmonberry Wine",
            "Slimejack",
            "Snow Yam",
            "Spice Berry Wine",
            "Spook Fish",
            "Stardrop",
            "Starfruit",
            "Starfruit Wine",
            "Strawberry",
            "Strawberry Wine",
            "Sturgeon",
            "Super Cucumber",
            "Tiger Trout",
            "Truffle",
            "Truffle Oil",
            "Tuna",
            "Vinegar",
            "Void Salmon",
            "Walleye",
            "Wild Plum Wine",
            "Wine (from Traveling Cart)",
            "Yam"
          ],
          silver: [
            "Albacore",
            "Amaranth",
            "Angler",
            "Apple",
            "Apricot Wine",
            "Artichoke",
            "Beer",
            "Beet",
            "Blackberry Wine",
            "Blueberry Wine",
            "Bok Choy",
            "Bullhead",
            "Cactus Fruit",
            "Cactus Fruit Wine",
            "Catfish",
            "Cauliflower",
            "Chanterelle",
            "Cheese",
            "Cherry",
            "Cherry Wine",
            "Cranberries",
            "Cranberries Wine",
            "Crystal Fruit",
            "Dorado",
            "Duck Egg",
            "Eel",
            "Fairy Rose",
            "Fiddlehead Fern",
            "Glacierfish",
            "Goat Milk",
            "Grape",
            "Grape Wine",
            "Halibut",
            "Hazelnut",
            "Hot Pepper Wine",
            "Kale",
            "Large Egg (white/brown)",
            "Large Milk",
            "Largemouth Bass",
            "Lingcod",
            "Mead",
            "Melon",
            "Midnight Squid",
            "Milk",
            "Morel",
            "Mutant Carp",
            "Orange",
            "Peach",
            "Pike",
            "Pomegranate",
            "Poppy",
            "Potato",
            "Purple Mushroom",
            "Radish",
            "Red Cabbage",
            "Red Mullet",
            "Salmon",
            "Salmonberry Wine",
            "Sandfish",
            "Slimejack",
            "Snow Yam",
            "Spice Berry",
            "Spice Berry Wine",
            "Spook Fish",
            "Squid",
            "Strawberry",
            "Sturgeon",
            "Summer Spangle",
            "Sunflower",
            "Super Cucumber",
            "Tiger Trout",
            "Tilapia",
            "Truffle",
            "Tuna",
            "Void Salmon",
            "Walleye",
            "Wild Plum",
            "Wild Plum Wine",
            "Winter Root",
            "Woodskip",
            "Yam"
          ],
          "Gold/Iridium": [
            "Albacore', 'Amaranth', 'Apple', 'Apricot Wine', 'Beet', 'Blackberry Wine', 'Blueberry Wine', 'Bok Choy', 'Bullhead', 'Cactus Fruit', 'Cherry', 'Cranberries', 'Crystal Fruit', 'Dorado', 'Duck Egg', 'Eel', 'Fiddlehead Fern', 'Grape', 'Halibut', 'Hazelnut', 'Hot Pepper Wine', 'Kale', 'Large Egg (white/brown)', 'Largemouth Bass', 'Lingcod', 'Milk', 'Morel', 'Orange', 'Peach', 'Pike', 'Pomegranate', 'Poppy', 'Potato', 'Radish', 'Red Mullet', 'Salmon', 'Salmonberry Wine', 'Sandfish', 'Slimejack', 'Snow Yam', 'Spice Berry', 'Squid', 'Strawberry', 'Summer Spangle', 'Sunflower', 'Tiger Trout', 'Tilapia', 'Tuna', 'Void Salmon', 'Walleye', 'Wild Plum', 'Winter Root', 'Woodskip"
          ]
        }
      }
    },
    {
      day: 13,
      name: "Alex",
      type: "birthday",
      loves: ["Complete Breakfast", "Salmon Dinner"],
      likes: ["Eggs"]
    },
    {
      day: 17,
      name: "Sam",
      type: "birthday",
      loves: ["Cactus Fruit", "Maple Bar", "Pizza", "Tigerseye"],
      likes: ["Eggs", "Joja Cola"]
    },
    {
      day: 19,
      name: "Demetrius",
      type: "birthday",
      loves: ["Bean Hotpot", "Ice Cream", "Rice Pudding", "Strawberry"],
      likes: ["Eggs", "Fruit", "Purple Mushroom"]
    },
    {
      day: 22,
      name: "Dwarf",
      type: "birthday",
      loves: [
        "Amethyst",
        "Aquamarine",
        "Emerald",
        "Jade",
        "Omni Geode",
        "Ruby",
        "Topaz"
      ],
      likes: ["Dwarf Gadget", "Dwarf Scrolls", "Dwarvish Helm", "Quartz"]
    },
    {
      day: 24,
      name: "Willy",
      type: "birthday",
      loves: [
        "Catfish",
        "Diamond",
        "Iridium Bar",
        "Mead",
        "Octopus",
        "Pumpkin",
        "Sea Cucumber",
        "Sturgeon"
      ],
      likes: [
        "Gold Bar",
        "Quartz",
        "Lingcod",
        "Tiger Trout",
        "Fish-related cooking"
      ]
    },
    { day: 28, name: "Moonlight Jellies", type: "event" }
  ],
  fall: [
    {
      day: 2,
      name: "Penny",
      type: "birthday",
      loves: [
        "Diamond",
        "Emerald",
        "Melon",
        "Poppy",
        "Poppyseed Muffin",
        "Red Plate",
        "Roots Platter",
        "Sandfish",
        "Tom Kha Soup"
      ],
      likes: ["Milk", "Dandelion", "Leek"]
    },
    {
      day: 5,
      name: "Elliott",
      type: "birthday",
      loves: [
        "Crab Cakes",
        "Duck Feather",
        "Lobster",
        "Pomegranate",
        "Tom Kha Soup"
      ],
      likes: ["Fruit", "Octopus", "Squid"]
    },
    {
      day: 11,
      name: "Jodi",
      type: "birthday",
      loves: [
        "Chocolate Cake",
        "Crispy Bass",
        "Diamond",
        "Eggplant Parmesan",
        "Fried Eel",
        "Pancakes",
        "Rhubarb Pie",
        "Vegetable Medley"
      ],
      likes: ["Eggs (except Void Egg)", "Fruit (except Spice Berry)", "Milk"]
    },
    {
      day: 13,
      name: "Abigail",
      type: "birthday",
      loves: [
        "Amethyst",
        "Blackberry Cobbler",
        "Chocolate Cake",
        "Pufferfish",
        "Pumpkin",
        "Spicy Eel"
      ],
      likes: ["Quartz"]
    },
    {
      day: 15,
      name: "Sandy",
      type: "birthday",
      loves: ["Crocus", "Daffodil", "Sweet Pea"],
      likes: ["Goat Milk", "Quartz", "Wool"]
    },
    {
      day: 16,
      name: "Stardew Valley Fair",
      type: "event",
      items: [
        "Animal Product",
        "Artisan Good",
        "Cooking",
        "Fish",
        "Foraging",
        "Fruit",
        "Vegetable",
        "Mineral"
      ]
    },
    {
      day: 18,
      name: "Marnie",
      type: "birthday",
      loves: ["Diamond", "Farmer's Lunch", "Pink Cake", "Pumpkin Pie"],
      likes: ["Eggs", "Milk", "Quartz"]
    },
    {
      day: 21,
      name: "Robin",
      type: "birthday",
      loves: ["Goat Cheese", "Peach", "Spaghetti"],
      likes: ["Milk", "Fruit", "Hardwood", "Quartz"]
    },
    {
      day: 24,
      name: "George",
      type: "birthday",
      loves: ["Fried Mushroom", "Leek"],
      likes: ["Daffodil"]
    },
    { day: 27, name: "Spirit's Eve Festival", type: "event" }
  ],
  winter: [
    {
      day: 1,
      name: "Krobus",
      type: "birthday",
      loves: [
        "Diamond",
        "Iridium Bar",
        "Pumpkin",
        "Void Egg",
        "Void Mayonnaise",
        "Wild Horseradish"
      ],
      likes: ["Gold Bar", "Quartz"]
    },
    {
      day: 3,
      name: "Linus",
      type: "birthday",
      loves: [
        "Blueberry Tart",
        "Cactus Fruit",
        "Coconut",
        "Dish o' The Sea",
        "Yam"
      ],
      likes: [
        "Chanterelle",
        "Common Mushroom",
        "Daffodil",
        "Dandelion",
        "Hazelnut",
        "Holly",
        "Leek",
        "Morel",
        "Purple Mushroom",
        "Snow Yam",
        "Spring Onion",
        "Wild Horseradish",
        "Winter Root"
      ]
    },
    {
      day: 7,
      name: "Caroline",
      type: "birthday",
      loves: ["Fish Taco", "Summer Spangle"],
      likes: ["Daffodil"]
    },
    { day: 8, name: "Festival of Ice", type: "event" },
    {
      day: 10,
      name: "Sebastian",
      type: "birthday",
      loves: ["Frozen Tear", "Obsidian", "Pumpkin Soup", "Sashimi", "Void Egg"],
      likes: ["Quartz"]
    },
    {
      day: 14,
      name: "Harvey",
      type: "birthday",
      loves: ["Coffee", "Pickles", "Super Meal", "Truffle Oil", "Wine"],
      likes: [
        "Fruit",
        "Chanterelle",
        "Common Mushroom",
        "Daffodil",
        "Dandelion",
        "Duck Egg",
        "Duck Feather",
        "Goat Milk",
        "Hazelnut",
        "Holly",
        "Leek",
        "Morel",
        "Purple Mushroom",
        "Quartz",
        "Snow Yam",
        "Spring Onion",
        "Wild Horseradish",
        "Winter Root"
      ]
    },
    {
      day: 17,
      name: "Wizard",
      type: "birthday",
      loves: [
        "Purple Mushroom",
        "Solar Essence",
        "Super Cucumber",
        "Void Essence"
      ],
      likes: ["Geode Minerals", "Quartz"]
    },
    {
      day: 20,
      name: "Evelyn",
      type: "birthday",
      loves: [
        "Beet",
        "Chocolate Cake",
        "Diamond",
        "Fairy Rose",
        "Stuffing",
        "Tulip"
      ],
      likes: ["Milk", "Daffodil"]
    },
    {
      day: 23,
      name: "Leah",
      type: "birthday",
      loves: [
        "Goat Cheese",
        "Poppyseed Muffin",
        "Salad",
        "Stir Fry",
        "Truffle",
        "Vegetable Medley",
        "Wine"
      ],
      likes: [
        "Eggs (except Void Egg)",
        "Fruit",
        "Milk",
        "Chanterelle",
        "Common Mushroom",
        "Daffodil",
        "Dandelion",
        "Driftwood",
        "Hazelnut",
        "Holly",
        "Leek",
        "Morel",
        "Purple Mushroom",
        "Snow Yam",
        "Spring Onion",
        "Wild Horseradish",
        "Winter Root"
      ]
    },
    { day: 25, name: "Flower Dance", type: "event" },
    {
      day: 26,
      name: "Clint",
      type: "birthday",
      loves: [
        "Amethyst",
        "Aquamarine",
        "Artichoke Dip",
        "Emerald",
        "Fiddlehead Risotto",
        "Gold Bar",
        "Iridium Bar",
        "Jade",
        "Omni Geode",
        "Ruby",
        "Topaz"
      ],
      likes: ["Copper Bar", "Iron Bar"]
    }
  ]
};
